### ISSUE TITLE
Multiple span references make spans lose their parent ID

### ISSUE THREAD

**Issue by william-tran** [honeycombio/opentelemetry-exporter-go#69]
```java
@Test
public void testMultipleParentSameTrace() {
    Span root = tracer.buildSpan("test-multi-parent-root").start();
    root.finish();
    Span span1 = tracer.buildSpan("test-multi-parent-span1").asChildOf(root).start();
    span1.finish();
    Span span2 = tracer.buildSpan("test-multi-parent-span2").asChildOf(root).start();
    span2.finish();
    Span span3 = tracer.buildSpan("test-multi-parent-span3").asChildOf(span1).asChildOf(span2).start();
    span3.finish();
}
```

![image](https://user-images.githubusercontent.com/1084441/78915011-4a924780-7a59-11ea-9714-94790630c332.png)

![image](https://user-images.githubusercontent.com/1084441/78915768-6b0ed180-7a5a-11ea-81b1-000ca9bd6f9e.png)

I'm not sure if this is just a UI issue or if the data model is supposed to work this way. Steps to repro:

Fire up `otel/opentelemetry-collector-contrib-dev:78e81f4ace962f8b613d5496218830cf05907c0f` (latest to date) with this config:

```
receivers:
  jaeger:
    protocols:
      thrift_http:
exporters:
  honeycomb:
    api_key: ***
    dataset: "test"
    api_url: "https://api.honeycomb.io"
service:
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [honeycomb]
```
port forward 14268, clone https://github.com/william-tran/tracing-tests and run `mvn test`
